# Generated by Django 3.1.3 on 2025-11-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hankki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchboxmodel',
            options={'permissions': [('lunchbox_supplier', '도시락 판매자')]},
        ),
    ]
