# Generated by Django 3.1.3 on 2025-11-27 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hankki', '0002_auto_20251127_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', '주문 대기'), ('PREPARING', '상품 준비 중'), ('READY_PICKUP', '픽업 준비 완료'), ('IN_DELIVERY', '배송 중'), ('COMPLETED', '완료'), ('CANCELLED', '주문 취소')], max_length=20)),
                ('price', models.IntegerField()),
                ('pickup_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_delivery', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lunchbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hankki.lunchboxmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hankki.ordermodel')),
            ],
        ),
    ]
