# Generated by Django 5.2.8 on 2025-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hankki", "0002_auto_20251127_0144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lunchboxmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
