# Generated by Django 3.1.3 on 2025-11-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankki', '0004_cartitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchboxmodel',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
