# Generated by Django 3.1.3 on 2025-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankki', '0005_auto_20251127_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchboxmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lunchbox/'),
        ),
    ]
