# Generated by Django 3.1.3 on 2025-11-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankki', '0006_lunchboxmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allergy', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lunchboxmodel',
            name='ingredient',
            field=models.ManyToManyField(blank=True, null=True, to='hankki.IngredientsModel'),
        ),
    ]
