# Generated by Django 3.1.3 on 2025-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankki', '0007_auto_20251129_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
